# Generated by Django 4.2.28 on 2026-04-24 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('codAula', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('codCarrera', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('codHorario', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(choices=[('LU', 'Lunes'), ('MA', 'Martes'), ('MI', 'Miércoles'), ('JU', 'Jueves'), ('VI', 'Viernes')], max_length=2)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('codSemestre', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paralelo',
            fields=[
                ('codParalelo', models.AutoField(primary_key=True, serialize=False)),
                ('numeroParalelo', models.CharField(max_length=10)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.aula')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.carrera')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.semestre')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('codMateria', models.AutoField(primary_key=True, serialize=False)),
                ('materiaID', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.semestre')),
            ],
        ),
    ]
