# Generated by Django 4.2.28 on 2026-04-24 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docente', '0001_initial'),
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaciondocente',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docente.docente'),
        ),
        migrations.AddField(
            model_name='asignaciondocente',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.horario'),
        ),
        migrations.AddField(
            model_name='asignaciondocente',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.materia'),
        ),
        migrations.AddField(
            model_name='asignaciondocente',
            name='paralelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.paralelo'),
        ),
    ]
