# Generated by Django 4.2.28 on 2026-04-24 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0002_initial'),
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('hora_ingreso', models.TimeField(auto_now_add=True)),
                ('asignacion_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.asignaciondocente')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante')),
            ],
        ),
    ]
